---
title: "EDA"
output: html_document
date: '2022-05-03'
---

```{r, echo = FALSE, message = FALSE}
source(here::here("scripts/setup.R"))
```

-------------------------------------------------------------------

NOUVEAU / EDA

-------------------------------------------------------------------



# Exploratory Data Analysis 

Let's import the dataset. 

```{r}
Beef_data <- read.csv2("../Data/BeefPrice.csv")
Commodity_Price_index <- read.csv("../Data/Commodity.price.index.csv")
Beef_production_world <- read.csv("../Data/beef-and-buffalo-meat-production-tonnes.csv")
Beef_US_price <- read.csv("../Data/Beef_price_US.csv")
Corn_price_US <- read.csv('../Data/corn_price_US.csv')
Corn_price <- read_delim('../Data/corn-prices-historical-chart-data.csv', 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)
Beef_consumption <- read_csv('../Data/Beef_consumption.csv')
Nasdaq <- read.csv('../Data/^NDX.csv') 
```


## Primary analysis of the database

```{r}
str(Beef_data)
str(Commodity_Price_index)
str(Beef_production_world)
str(Beef_US_price)
```

```{r}
which(is.na(Beef_data))
which(is.na(Commodity_Price_index))
which(is.na(Beef_production_world))
which(is.na(Beef_US_price))
```


```{r}
names(Beef_data)[2] <- 'Global_price_of_beef'

Beef_data$Global_price_of_beef <- as.numeric(Beef_data$Global_price_of_beef)

Beef_data$DATE <- as.Date(Beef_data$DATE, format = "%Y-%m-%d")



Beef_data.tsibble <- Beef_data %>%
  mutate(DATE = yearmonth(DATE)) %>%
  as_tsibble(index = DATE)

```

```{r}
names(Commodity_Price_index)[2] <- 'Price_index'

Commodity_Price_index$Price_index<- as.numeric(Commodity_Price_index$Price_index)

Commodity_Price_index$DATE<- as.Date(Commodity_Price_index$DATE, format = "%Y-%m-%d")



Commodity_Price.tsibble <- Commodity_Price_index %>%
  mutate(DATE = yearmonth(DATE)) %>%
  as_tsibble(index = DATE)

```


```{r}
names(Beef_US_price)[2] <- 'US_beef_price'

Beef_US_price$US_beef_price<- as.numeric(Beef_US_price$US_beef_price)

Beef_US_price$DATE<- as.Date(Beef_US_price$DATE, format = "%Y-%m-%d")



Beef_US_price.tsibble <- Beef_US_price %>%
  na_interpolation()%>%
  mutate(DATE = yearmonth(DATE)) %>%
  as_tsibble(index = DATE)

library(imputeTS)
Beef_US_price.tsibble <- na_interpolation(Beef_US_price.tsibble)
Beef_US_price.tsibble[2] <- Beef_US_price.tsibble[2]*100

```

```{r}
Beef_US_production <- Beef_production_world %>%
  filter(Entity == 'United States')
Beef_US_production <- Beef_US_production[,-(1:2)]

names(Beef_US_production)[1] <- 'DATE'
names(Beef_US_production)[2] <- 'US_beef_production'

Beef_US_production$US_beef_production<- as.numeric(Beef_US_production$US_beef_production)
Beef_US_production$DATE<- as.numeric(Beef_US_production$DATE)

Beef_US_production$DATE <- as.Date(as.character(Beef_US_production$DATE), format = "%Y")


Beef_US_production.tsibble <- Beef_US_production %>%
  mutate(DATE = year(DATE)) %>%
  as_tsibble(index = DATE)
```



```{r}
names(Corn_price_US)[2] <- 'US_corn_price'

Corn_price_US$US_corn_price<- as.numeric(Corn_price_US$US_corn_price)

Corn_price_US$DATE<- as.Date(Corn_price_US$DATE, format = "%Y-%m-%d")



Corn_price_US.tsibble <- Corn_price_US %>%
  mutate(DATE = yearmonth(DATE)) %>%
  as_tsibble(index = DATE)

```

```{r}
names(Corn_price)[2] <- 'corn_price'

Corn_price$corn_price<- as.numeric(Corn_price$corn_price)

Corn_price$date<- as.Date(Corn_price$date, format = "%Y-%m-%d")



Corn_price.tsibble <- Corn_price %>%
  as_tsibble(index = date)
```


```{r}
US_Beef_consumption <- Beef_consumption %>%
  filter(LOCATION == 'USA')
US_Beef_consumption <- US_Beef_consumption[,-(1:5)]
US_Beef_consumption <- US_Beef_consumption[,-3]

names(US_Beef_consumption)[1] <- 'DATE'
names(US_Beef_consumption)[2] <- 'US_beef_consumption'

US_Beef_consumption$US_beef_consumption<- as.numeric(US_Beef_consumption$US_beef_consumption)
US_Beef_consumption$DATE<- as.numeric(US_Beef_consumption$DATE)

US_Beef_consumption$DATE <- as.Date(as.character(US_Beef_consumption$DATE), format = "%Y")


US_Beef_consumption.ts <- US_Beef_consumption %>%
  mutate(DATE = year(DATE)) %>%
  as_tsibble(index = DATE)
```


```{r}
Annual_US_beef.price <- Beef_US_price
Annual_US_beef.price$DATE <- as.Date(Annual_US_beef.price$DATE )
Annual_US_beef.price$Year <- year(Annual_US_beef.price$DATE)
Annual_US_beef.price$Year <- format(Annual_US_beef.price$DATE,format="%Y")
Annual_US_beef.price <- aggregate(US_beef_price ~ Year, Annual_US_beef.price, mean)
Annual_US_beef.price[2] <- Annual_US_beef.price[2]*100

Annual_US_beef.price$Year <- as.Date(as.character(Annual_US_beef.price$Year), format = "%Y")

Annual_US_beef.price.ts <- Annual_US_beef.price %>%
  mutate(Year = year(Year)) %>%
  as_tsibble(index = Year)

Annual_US_beef.price.ts %>% autoplot()
names(Annual_US_beef.price.ts)[1] <- 'DATE'
```

```{r}
Nasdaq <- Nasdaq[-c(2:4,6:7)]
names(Nasdaq)[1] <- 'DATE'
Nasdaq$DATE <- as.Date(as.character(Nasdaq$DATE), format = "%Y-%m-%d")
Nasdaq.tsibble <- Nasdaq %>%
  mutate(DATE = yearmonth(DATE)) %>%
  as_tsibble(index = DATE)
```


